### ISSUE TITLE
Punishment alerts

### ISSUE THREAD

**Issue by noClaps** [Mester-Ulquiorra/web#11]

**Comment by MesterMan03** [comment]
**API update**

The `/ws` route now returns a "punishment" alert.
The data parameter is the same structure as the punishment object from `/user/punishment`.
In test mode, the `/ws` route returns both a test appeal alert and a test punishment alert.

**Comment by noClaps** [comment]
Will punishment have a `status` value? If not, see PR #12 

Also, the `punishmentId` value is different to the `id ` value in `/user/punishment`, so I can't extend the type with that. You should rename it to `id`.

**Comment by MesterMan03** [comment]
> Also, the `punishmentId` value is different to the `id ` value in `/user/punishment`, so I can't extend the type with that. You should rename it to `id`.

Well that is an API bug then, it is supposed to be `punishmentId`, I'm going to fix that right now, but let me know when the frontend is ready, so I don't push API updates that break it.

**Comment by noClaps** [comment]
Differences between `PunishmentData` and `AlertData<"punishment">`:

```diff
{
-  id: string;
+  punishmentId: string;
-  user: string;
-  moderator: string;
+  mod: string;
  type: number;
  reason: string;
  at: number;
  until: number;
  active: boolean;
  appealed: boolean;
}
```

**Comment by noClaps** [comment]
The changes are ready in PR #13
